import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { FormBuilderProvider, SectionProvider } from "../contexts";
import { ReactQueryProvider } from "@/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        style={{ backgroundColor: "#ecf4f8" }}
        className={inter.className}
      >
        <ReactQueryProvider>
          <FormBuilderProvider>
            <SectionProvider>{children}</SectionProvider>
          </FormBuilderProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
