import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SectionProvider } from "../contexts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        style={{ backgroundColor: "#ecf4f8" }}
        className={inter.className}
      >
        <SectionProvider>{children}</SectionProvider>
      </body>
    </html>
  );
}
