import { Box, Typography } from "@mui/material";
export * from "./buttons";
export * from "./tables";
export * from "./form";
export * from "./cards";
export * from "./stepper";
export * from "./theme/colors";
export * from "./header";
export const WrapperBox = Box;
export const MainTypography = Typography;
