import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "@/components";
import { ProviderTheme } from "@/components/providers";
import { ReactQueryProvider } from "@/providers";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <ReactQueryProvider>
          <ProviderTheme>
            <NavBar />
            {children}
            <ToastContainer />
          </ProviderTheme>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
